import CircularProgress from '@mui/material/CircularProgress';
import type { Metadata } from 'next';
import dynamic from 'next/dynamic';
import React, { useMemo } from 'react';
import './globals.css';

export const metadata: Metadata = {
  title: 'Pisek pruvodce',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const UserProvider = useMemo(
    () =>
      dynamic(() => import('@/context/UserContext'), {
        loading: () => <CircularProgress />,
        ssr: false,
      }),
    [],
  );

  return (
    <html lang="cs">
      <body>
        <UserProvider>{children}</UserProvider>
      </body>
    </html>
  );
}
